name: Tag workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Creating a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@starkware-industries'

      - name: Install dependencies
        run: yarn

      - name: Build project 🔧
        run: yarn run build

      - name: Publish package on NPM 📦
        run: yarn npm-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
